-- USERS TABLE
CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email TEXT UNIQUE NOT NULL,
	entries BIGINT DEFAULT 0,
	joined TIMESTAMP NOT NULL
);

-- login TABLE
CREATE TABLE login (
	id SERIAL PRIMARY KEY,
	hash VARCHAR(100) NOT NULL,
	email TEXT UNIQUE NOT NULL
);